# Generated by Django 2.2.9 on 2020-02-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='count',
            new_name='votes',
        ),
    ]
