# Generated by Django 2.2.9 on 2020-02-11 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20200211_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='file/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
