# Generated by Django 2.2.9 on 2020-02-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20200211_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='Running For'),
        ),
        migrations.AlterField(
            model_name='person',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
